# Generated by Django 5.0.6 on 2024-05-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=10, verbose_name='작성자'),
        ),
    ]
